services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "80:80"
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - ./Back-end/src/main/resources/static:/app/build
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost/users
    depends_on:
      - backend
    networks:
      - website



  backend:
    image: eclipse-temurin:21-jdk-alpine
    container_name: spring-app
    volumes:
      - ./Back-end/target/home-services-booking-0.0.1-SNAPSHOT.jar:/app/app.jar
      - ./Back-end/data:/Back-end/data
    working_dir: /app
    command: ["java", "-jar", "app.jar", "--spring.profiles.active=dev"]
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - website

volumes:
  data:

networks:
  website:
    driver: bridge
