services:
  frontend:
    image: nginx:alpine
    container_name: site
    ports:
      - "80:80"
    volumes:
      - ./Back-end/src/main/resources/static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - website

  backend:
    image: eclipse-temurin:21-jdk-alpine
    container_name: spring-app
    volumes:
      - ./Back-end/target/home-services-booking-0.0.1-SNAPSHOT.jar:/app/app.jar
      - ./Back-end/data:/Back-end/data
    working_dir: /app
    command: ["java", "-jar", "app.jar", "--spring.profiles.active=dev"]
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - website

volumes:
  data:

networks:
  website:
    driver: bridge
