server:
  servlet:
    context-path: /
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://db:5432/db
    #url: jdbc:postgresql://localhost:5434/db
    username: postgres 
    password: ${POSTGRES_PASSWORD}
    # password: myNotSoSecretPassword
    driver-class-name: org.postgresql.Driver 
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        batch_size: 50 
      temp:
        use_jdbc_metadata_defaults: false 
    properties:
      hibernate:
        ddl-auto: update 
        show_sql: true 
    open-in-view: false

app:
  users:
    file: data/users.json
