server:
  servlet:
    context-path: /odm
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://db:5432/nom_de_ta_base 
    username: postgres 
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver 
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        batch_size: 50 
      temp:
        use_jdbc_metadata_defaults: false 
    properties:
      hibernate:
        ddl-auto: update 
        show_sql: true 
    open-in-view: false

server:
  servlet:
    context-path: /odm 
  port: 8080 
