spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/db
    username: postgres
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true


app:
  users:
    file: data/users.json
  messages:
    file: data/messages.json
  prestataires:
    file: data/prestataires.json
  avis:
    file: data/avis.json
  paiements:
    file: data/paiements.json
  reservations:
    file: data/reservations.json
  services:
    file: data/services.json
  image:
    dir: data/image
